services:
  db:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"

  frontend:
    build:
      dockerfile: ./build/frontend.Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      dockerfile: ./build/backend.Dockerfile
    env_file: .env
    ports:
      - "3030:3030"
    depends_on:
      - db

networks:
  my-network:
    driver: bridge
